// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/db push use a direct (unpooled) connection when available;
    // the runtime client (src/lib/prisma.ts) uses DATABASE_URL (pooled in prod).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
